version: '2'
services:
  web:
    image: node
    working_dir: /code
    command: npx nodemon
    volumes:
      - .:/code
    ports:
      - 3000:3000
  jupyter:
    build: ./jupyter.dockerfile
    volumes:
      - ./docs:/home/jovyan/docs
    ports:
      - 8888:8888
